imports:
    - { resource: "@PayumBundle/Resources/config/payum.xml" }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.


    payum.yadm_gateway_config_storage:
        class: Payum\Core\Storage\StorageInterface
        factory: ['App\Factory\GatewayConfigStorageFactory', create]
        arguments:
            - '@payum.gateway_config_storage'

    payum.gateway_config_storage: '@payum.storage._app_model_gatewayconfig'

    api.view.gateway_config_to_json_converter:
        class: App\Api\View\GatewayConfigToJsonConverter

    payum.gateway_schema_builder:
        class: App\Schema\GatewaySchemaBuilder
        arguments:
            - '@payum'

    App\JsonDecode: '@payum.json_decode'
    payum.json_decode:
        class: App\JsonDecode

    Payum\Core\Payum: '@payum'

    payum.builder:
        class: Payum\Core\PayumBuilder
        factory: 'payum.builder.facade:get'
        arguments:
            - '@payum.builder.factory'
            - '@payum.security.token_storage'
            - '@payum.yadm_gateway_config_storage'
            - '@payum.payment_storage'
            - '@form.factory'
            - '@twig'

    payum.builder.factory:
        class: Payum\Core\PayumBuilder

    payum.builder.facade:
        class: App\Facade\PayumBuilderFacade

    payum.security.token_storage: '@payum.storage._app_model_securitytoken'

    App\Storage\PaymentStorage: '@payum.storage._app_model_payment'
    payum.payment_storage: '@payum.storage._app_model_payment'

    payum.server.schema.gateway_form_definition_builder:
        class: App\Schema\GatewayFormDefinitionBuilder
        arguments:
            - '@payum'

    App\Schema\PaymentSchemaBuilder: '@payum.payment_schema_builder'
    payum.payment_schema_builder:
        class: App\Schema\PaymentSchemaBuilder
        arguments:
            - '@payum.yadm_gateway_config_storage'

    payum.payment_form_definition_builder:
        class: App\Schema\PaymentFormDefinitionBuilder
        arguments:
            - '@payum.yadm_gateway_config_storage'

    App\Schema\TokenSchemaBuilder: '@payum.token_schema_builder'
    payum.token_schema_builder:
        class: App\Schema\TokenSchemaBuilder

    App\Api\View\PaymentToJsonConverter: '@api.view.payment_to_json_converter'
    api.view.payment_to_json_converter:
        class: App\Api\View\PaymentToJsonConverter
        arguments:
            - '@payum'

    App\Api\View\TokenToJsonConverter: '@api.view.token_to_json_converter'
    api.view.token_to_json_converter:
        class: App\Api\View\TokenToJsonConverter

    payum.core_gateway_factory_builder:
        public: true
        class: Payum\Core\Bridge\Symfony\Builder\CoreGatewayFactoryBuilder
        calls:
            - [setContainer, ['@service_container']]

#    App\Form\Type\ChooseGatewayType: '@payum.server.form.type.choose_gateway_type'
#    payum.server.form.type.choose_gateway_type:
#        class: App\Form\Type\ChooseGatewayType
#        arguments:
#            - '@payum.gateway_choices_callback'
#
#    App\Factory\GatewayChoicesCallbackFactory: '@payum.gateway_choices_callback'
#    payum.gateway_choices_callback:
#        class: callback
#        factory: ['App\Factory\GatewayChoicesCallbackFactory', create]
#        arguments:
#            - '@service_container'

    # controller gateways
    payum.api.controller.gateway:
        class: App\Api\Controller\GatewayController
        public: true
        arguments:
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
            - '@payum.yadm_gateway_config_storage'
            - '@api.view.gateway_config_to_json_converter'
            - '@payum.gateway_schema_builder'
            - '@payum.json_decode'

    # controller schema gateways
    payum.schema.controller.gateways:
        class: App\Schema\Controller\GatewaySchemaController
        public: true
        arguments:
            - '@payum.gateway_schema_builder'
            - '@payum.server.schema.gateway_form_definition_builder'

    # controller schema payments
    payum.schema.controller.payments:
        class: App\Schema\Controller\PaymentSchemaController
        public: true
        arguments:
            - '@payum.payment_schema_builder'
            - '@payum.payment_form_definition_builder'

    # controller schema tokens
    payum.schema.controller.tokens:
        class: App\Schema\Controller\TokenSchemaController
        public: true
        arguments:
            - '@payum.token_schema_builder'

    # controller payment
    payum.api.controller.payment:
        class: App\Api\Controller\PaymentController
        public: true

    # controller payment
    payum.api.controller.token:
        class: App\Api\Controller\TokenController
        public: true

    # event request
    payum.listener.choose_gateway:
        class: App\EventListener\Request\GatewayChooserListener
        tags:
            - { name: kernel.event_subscriber }