payum:
    storages:
        App\Model\Payment:
            yadm: ~

    security:
        token_storage:
            App\Model\SecurityToken:
                yadm:
                    id_property: hash

    gateways:
        offline:
            factory: offline

        stripe_checkout:
            factory: stripe_checkout
            publishable_key: "EDIT IT"
            secret_key: "EDIT IT"

    dynamic_gateways:
        config_storage:
            App\Model\GatewayConfig:
                yadm: ~