language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

services: mongodb

before_install:
    - pecl install mongodb
    - composer self-update

install:
    - composer --prefer-source install

notifications:
  email:
    - payumsupport@forma-pro.com
