language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer

services:
  - mongodb
  - docker

before_install:
    - pecl install mongodb

install:
    - ./bin/composer install

after_success:
  - rm -rf vendor
  - ./bin/composer install --optimize-autoloader --classmap-authoritative --no-dev --no-suggest --prefer-dist
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=payum/payum-server
  - export if [ "$TRAVIS_BRANCH" == "master" ]; then TAG="latest"; else exit ; fi
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

notifications:
  email:
    - payumsupport@forma-pro.com
