language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer

services:
  - mongodb
  - docker

before_install:
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install

script:
    - bin/phpunit

after_success:
  - rm -rf vendor
  - composer install --optimize-autoloader --classmap-authoritative --no-dev --no-suggest --prefer-dist
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=payum/payum-server
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "" ; fi`
  - if [ -z "$TAG" ]; then docker build -f Dockerfile -t $REPO:$COMMIT .; fi
  - if [ -z "$TAG" ]; then docker tag $REPO:$COMMIT $REPO:$TAG; fi
  - if [ -z "$TAG" ]; then docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER; fi
  - if [ -z "$TAG" ]; then docker push $REPO; fi

notifications:
  email:
    - payumsupport@forma-pro.com
