language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer

services: mongodb

before_install:
    - pecl install mongodb

install:
    - ./bin/composer install

notifications:
  email:
    - payumsupport@forma-pro.com
