version: '2'

services:
  payum-server:
    image: payum/payum-server
    build: .
#    container_name: payum-server
    restart: always
    environment:
      PAYUM_MONGO_URI: 'mongodb://mongo:27017/payum_server'
      PAYUM_DEBUG: 1
      VIRTUAL_HOST: 'payum-server.loc'
      DEFUSE_SECRET: 'def000007e98fe20fc86559bc6de11ecbc1cf052d872ad864d4865a1e93ad0fac00e93db865b611a01d2f15db7c45c81ce71d54334fffb26440080d6bb616b0bba148373'
    links:
      - mongo
    volumes:
      - .:/payum

#  payum-server-ui:
#    image: payum/server-ui
#    container_name: payum-server-ui
#    restart: always
#    environment:
#      - VIRTUAL_HOST=payum-server-ui.loc
#    volumes:
#      - ../PayumServerUI:/payum

  mongo:
    image: mongo
#    container_name: payum-mongo
    restart: always
    volumes:
      - ./backup:/backup
    ports:
      - "27017:27017"

  front:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro