version: '2'
services:
  web:
    build: .
    container_name: payum
    environment:
      - PAYUM_MONGO_URI=mongodb://mongo:27017/payum_server
      - PAYUM_DEBUG=1
      - VIRTUAL_HOST=payum.dev
    volumes:
      - .:/payum
    links:
      - mongo

  mongo:
    image: mongo

  nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro