services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # controller gateways
    payum.api.controller.gateway:
        class: App\Api\Controller\GatewayController
        public: true
        arguments:
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
            - '@payum.yadm_gateway_config_storage'
            - '@api.view.gateway_config_to_json_converter'
            - '@payum.gateway_schema_builder'
            - '@payum.json_decode'

    # controller schema gateways
    payum.schema.controller.gateways:
        class: App\Schema\Controller\GatewaySchemaController
        public: true
        arguments:
            - '@payum.gateway_schema_builder'
            - '@payum.server.schema.gateway_form_definition_builder'

    # controller schema payments
    payum.schema.controller.payments:
        class: App\Schema\Controller\PaymentSchemaController
        public: true
        arguments:
            - '@payum.payment_schema_builder'
            - '@payum.payment_form_definition_builder'

    # controller schema tokens
    payum.schema.controller.tokens:
        class: App\Schema\Controller\TokenSchemaController
        public: true
        arguments:
            - '@payum.token_schema_builder'

    # controller payment
    payum.api.controller.payment:
        class: App\Api\Controller\PaymentController
        public: true

    # controller payment
    payum.api.controller.token:
        class: App\Api\Controller\TokenController
        public: true
