# default
payum.schema.controller.gateways.default:
    path: /default.json
    methods: [GET]
    defaults:
        _controller: payum.schema.controller.gateways:getDefaultAction

# form default
payum.schema.controller.gateways.form.default:
    path: /form/default.json
    methods: [GET]
    defaults:
        _controller: payum.schema.controller.gateways:getDefaultFormAction

# action
payum.schema.controller.gateways.action:
    path: /{name}.json
    methods: [GET]
    defaults:
        _controller: payum.schema.controller.gateways:getAction

# form action
payum.schema.controller.gateways.form.action:
    path: /form/{name}.json
    methods: [GET]
    defaults:
        _controller: payum.schema.controller.gateways:getFormAction