imports:
    - { resource: events/payum.yaml }
    - { resource: controllers/payum.yaml }
    - { resource: "@PayumBundle/Resources/config/payum.xml" }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.


    payum.yadm_gateway_config_storage:
        class: Payum\Core\Storage\StorageInterface
        factory: ['Payum\Server\Factory\GatewayConfigStorageFactory', create]
        arguments:
            - '@payum.gateway_config_storage'

    payum.gateway_config_storage:
        public: true
        class: Makasim\Yadm\Storage
        arguments:
            - "@=service('mongodb.database').selectCollection('gateway_configs')"
            - '@yadm.hydrator.gateway'

    api.view.gateway_config_to_json_converter:
        class: Payum\Server\Api\View\GatewayConfigToJsonConverter

    payum.gateway_schema_builder:
        class: Payum\Server\Schema\GatewaySchemaBuilder
        arguments:
            - '@payum'

    Payum\Server\JsonDecode: '@payum.json_decode'
    payum.json_decode:
        class: Payum\Server\JsonDecode

    Payum\Core\Payum: '@payum'

    payum.builder:
        class: Payum\Core\PayumBuilder
        factory: 'payum.builder.facade:get'
        arguments:
            - '@payum.builder.factory'
            - '@payum.security.token_storage'
            - '@payum.yadm_gateway_config_storage'
            - '@payum.payment_storage'
            - '@form.factory'
            - '@twig'

    payum.builder.factory:
        class: Payum\Core\PayumBuilder

    payum.builder.facade:
        class: Payum\Server\Facade\PayumBuilderFacade

    payum.security.token_storage:
        public: true
        class: Makasim\Yadm\Storage
        arguments:
            - "@=service('mongodb.database').selectCollection('security_tokens')"
            - '@yadm.hydrator.security.token'

    Payum\Server\Storage\PaymentStorage: '@payum.payment_storage'
    payum.payment_storage:
        public: true
        class: Payum\Server\Storage\PaymentStorage
        arguments:
            - "@=service('mongodb.database').selectCollection('payments')"
            - '@yadm.hydrator.payment'

    payum.server.schema.gateway_form_definition_builder:
        class: Payum\Server\Schema\GatewayFormDefinitionBuilder
        arguments:
            - '@payum'

    Payum\Server\Schema\PaymentSchemaBuilder: '@payum.payment_schema_builder'
    payum.payment_schema_builder:
        class: Payum\Server\Schema\PaymentSchemaBuilder
        arguments:
            - '@payum.yadm_gateway_config_storage'

    payum.payment_form_definition_builder:
        class: Payum\Server\Schema\PaymentFormDefinitionBuilder
        arguments:
            - '@payum.yadm_gateway_config_storage'

    Payum\Server\Schema\TokenSchemaBuilder: '@payum.token_schema_builder'
    payum.token_schema_builder:
        class: Payum\Server\Schema\TokenSchemaBuilder

    Payum\Server\Api\View\PaymentToJsonConverter: '@api.view.payment_to_json_converter'
    api.view.payment_to_json_converter:
        class: Payum\Server\Api\View\PaymentToJsonConverter
        arguments:
            - '@payum'

    Payum\Server\Api\View\TokenToJsonConverter: '@api.view.token_to_json_converter'
    api.view.token_to_json_converter:
        class: Payum\Server\Api\View\TokenToJsonConverter

    payum.core_gateway_factory_builder:
        public: true
        class: Payum\Core\Bridge\Symfony\Builder\CoreGatewayFactoryBuilder
        calls:
            - [setContainer, ['@service_container']]

#    Payum\Server\Form\Type\ChooseGatewayType: '@payum.server.form.type.choose_gateway_type'
#    payum.server.form.type.choose_gateway_type:
#        class: Payum\Server\Form\Type\ChooseGatewayType
#        arguments:
#            - '@payum.gateway_choices_callback'
#
#    Payum\Server\Factory\GatewayChoicesCallbackFactory: '@payum.gateway_choices_callback'
#    payum.gateway_choices_callback:
#        class: callback
#        factory: ['Payum\Server\Factory\GatewayChoicesCallbackFactory', create]
#        arguments:
#            - '@service_container'
