payum.default:
    resource: ./routes/payum/default.yaml
    type: yaml

payum.gateways:
    resource: ./routes/payum/gateways.yaml
    prefix: /gateways
    type: yaml

payum.payment:
    resource: ./routes/payum/payment.yaml
    prefix: /payments
    type: yaml

payum.schema.token:
    resource: ./routes/payum/token.yaml
    prefix: /tokens
    type: yaml

# schema
payum.schema.gateways:
    resource: ./routes/payum/schema/gateways.yaml
    prefix: /schema/gateways
    type: yaml

payum.schema.payments:
    resource: ./routes/payum/schema/payments.yaml
    prefix: /schema/payments
    type: yaml

payum.schema.tokens:
    resource: ./routes/payum/schema/tokens.yaml
    prefix: /schema/tokens
    type: yaml

# payum bundle
payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"

payum_capture_do:
    path: /payment/capture/{payum_token}
    defaults:
        _controller: App\Controller\CaptureController::doAction

payum_authorize_do:
    path: /payment/authorize/{payum_token}
    defaults:
        _controller: App\Controller\AuthorizeController::doAction
