# all
gateway_all:
    path: /
    methods: [GET]
    defaults:
        _controller: payum.api.controller.gateway:allAction

# create
gateway_create:
    path: /
    methods: [POST]
    defaults:
        _controller: payum.api.controller.gateway:createAction

# get
gateway_get:
    path: /{name}
    methods: [GET]
    defaults:
        _controller: payum.api.controller.gateway:getAction

# delete
gateway_delete:
    path: /{name}
    methods: [DELETE]
    defaults:
        _controller: payum.api.controller.gateway:deleteAction